apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1 # default replicas, overridden in overlays
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: europe-central2-docker.pkg.dev/weather-app-demo-447410/backend-application-python/backend:1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: API_BASE_URL
              value: "https://api.publicapis.org/entries"
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: mongo-uri
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-password
                  key: mongo-password
