apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-mongo-password
  namespace: default
spec:
  schedule: "* * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-service-account
          containers:
            - name: update-mongo-password
              image: europe-central2-docker.pkg.dev/weather-app-demo-447410/backend-application-python/cron:1.0.0
              env:
                - name: ENV
                  value: "dev"
                - name: DEPLOYMENT_APP
                  value: "app"
              imagePullPolicy: IfnotPresent
          restartPolicy: OnFailure

