apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-role-binding
subjects:
  - kind: ServiceAccount
    name: cronjob-service-account
    namespace: default
roleRef:
  kind: Role
  name: cronjob-role
  apiGroup: rbac.authorization.k8s.io

