apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cronjob-role
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - create
      - delete
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups: ["apps"]
    resources:
      - deployments/scale
    verbs:
      - update
