apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-mongo-password
  namespace: default
spec:
  schedule: "* */5 * * *"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-mongo-password
              env:
                - name: ENV
                  value: "stage"
                - name: DEPLOYMENT_APP
                  value: "app"
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
