resources:
  - ../../base

namePrefix: stage-

patches:
  - target:
      kind: Deployment
      name: app
    patch: |-
      spec:
        replicas: 2
  - target:
      kind: Deployment
      name: db
    patch: |-
      spec:
        replicas: 1
